title: Persondataløsningen
description: >-
  Dokumentasjon for NAVs Persondataløsning. Dette systemet er NAVS masterdata-register for
  grunnleggende personopplysninger fra Folkeregisteret, NAV selv, samt andre kilder.
markdown: kramdown
collections:
  - opplysningstyper
exclude: [.idea]